spring:
  main:
    web-application-type: REACTIVE
  application:
    name: online-store-service
  profiles:
    active: local
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      #resourceserver:
        #jwt:
          #jwk-set-uri: http://localhost:4444/realms/playground-keycloak-service/protocol/openid-connect/certs
      client:
        registration:
          item-inventory-api:
            client-id: item-inventory-api
            client-secret: 5ptanrhy2H08qigXuHa7D55FvMD5wvFn
            #client-secret: JdYsFquJliE1rmqy4UgPwhPMjSySOkNhXavierSandbox
            authorization-grant-type: client_credentials
            scope: openid
          item-review-api:
            client-id: item-review-api
            client-secret: JdYsFquJliE1rmqy4UgPwhPMjSySOkNh
            #client-secret: 5ptanrhy2H08qigXuHa7D55FvMD5wvFnXaviersSandbox
            authorization-grant-type: client_credentials
            scope: openid  
        provider:
          keycloak:
            token-uri: http://localhost:4444/realms/playground-keycloak-service/protocol/openid-connect/token
            jwk-set-uri: http://localhost:4444/realms/playground-keycloak-service/protocol/openid-connect/certs


#client id - online-store-api
#client secret - zR8XNmemblnbx6Ki7mQGdqxGyNU4IXZw
#client secret - zR8XNmemblnbx6Ki7mQGdqxGyNU4IXZw
#client secret - zR8XNmemblnbx6Ki7mQGdqxGyNU4IXZw

server:
  port: 3333  

management:
  endpoints:
    web:
      exposure:
        include: "health,info"  

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka     
    enabled: false
    
springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui: 
    path: /swagger-ui.html 
    enabled: true
    #disable-swagger-default-url: false   
---
spring:
  config:
    activate:
      on-profile: local      
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

logging:
  level: 
    "[com.online.store]" : DEBUG     
    "[com.sandbox.util]" : DEBUG    

webClient:
  itemInventoriesUrl: http://localhost:1111/v1/item-inventories/app
  itemReviewsUrl: http://localhost:2222/v1/item-reviews/app

---
spring:
  config:
    activate:
      on-profile: test       
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
logging:
  level: 
    "[com.online.store]" : DEBUG     
    "[com.github.tomakehurst.wiremock]" : ERROR
    "[com.sandbox.util]" : DEBUG

webClient:
  itemInventoriesUrl: http://localhost:1111/v1/item-inventories/app
  itemReviewsUrl: http://localhost:2222/v1/item-reviews/app


