version: '3'

services:
#  mysql:
 #   image: mysql:latest
 #   restart: always
 #   ports:
 #   - "3306:3306"
 #   environment:
 #     MYSQL_DATABASE: item-inventory-consumer-app
 #     MYSQL_ALLOW_EMPTY_PASSWORD: yes
    
  mongodb:
    image: mongo
    restart: always
    ports:
    - "27017:27017"

  redis:
    image: redis
    restart: always
    ports:
    - "6379:6379"

  docker-item-review:
    image: item-review-image
    restart: always
    ports:
    - "2222:2222"
    environment:
      #SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/item-inventory-consumer-app?autoReconnect=true&useSSL=false
      SPRING_PROFILES_ACTIVE: "local"
      SPRING_DATA_MONGODB_HOST: mongodb
      SPRING_DATA_REDIS_HOST: redis
    depends_on:
       - mongodb
       - redis
  #  healthcheck:
   #   test: ["CMD", "curl", "-f", "http://localhost:2222/health", "http://localhost:2222/info"]
    #  interval: 90s
     # timeout: 8s
      #retries: 5