spring:
  application: 
    name: naming-server

server: 
  port: 8761
 
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka     
    enabled: true
    register-with-eureka: false
    fetch-registry: false
