spring:
  main:
    web-application-type: REACTIVE
  application:
    name: item-inventory-service
  profiles:
    active: local
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:4444/realms/playground-keycloak-service/protocol/openid-connect/certs

#client id - item-inventory-api
#client secret - 5ptanrhy2H08qigXuHa7D55FvMD5wvFn
#client secret - 5ptanrhy2H08qigXuHa7D55FvMD5wvFn
#client secret - 5ptanrhy2H08qigXuHa7D55FvMD5wvFn


server:
  port: 1111
  #forward-headers-strategy: framework

management:
  endpoints:
    web:
      exposure:
        include: "health,info"
        
eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka     
    enabled: false 
    
resilience4j:
  retry:
    instances:
      testing-circuit-breaker:
        maxAttempts: 3   
        waitDuration: 1s
        enableExponentialBackoff: true

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui: 
    path: /swagger-ui.html 
    enabled: true
    #disable-swagger-default-url: false

---
spring:
  config:
    activate:
      on-profile: local      
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local   
    redis:
      #host: 10.11.12.13
      host: localhost
      port: 6379

logging:
  level: 
    "[com.item.inventory]" : DEBUG   
    "[com.sandbox.util]" : DEBUG  
    #"[org.springframework.data.mongodb.core.MongoTemplate]": DEBUG
    #"[org.springframework.data.mongodb.core.ReactiveMongoTemplate]": DEBUG 

---
spring:
  config:
    activate:
      on-profile: test       
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
    redis:
      #host: 10.11.12.13
      host: localhost
      port: 6379
logging:
  level: 
    "[com.item.inventory]" : DEBUG     
    "[com.redis.sandbox]" : DEBUG   
    "[com.sandbox.util]" : DEBUG    
